### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by jiminycrick** [sdd/kiddo_v1#3]
Hi there.
Not sure if you were aware, but neither the git version nor the crates.io version compiles right now. I would list the errors here but there are 14.
Steps to reproduce:
`cargo check`, `cargo test`, `cargo bench` or try using `kiddo` in another project

**Comment by jiminycrick** [comment]
Fwiw, commenting out the custom_serde module allows it to compile

**Comment by jblindsay** [comment]
I've encountered this same compilation error. I get about 22 errors listed when I try to compile the crates.io version. Many of the errors seem to be related to serde, although not all.

**Comment by sdd** [comment]
Sorry, only just seen this, I get a bit swamped in GitHub emails. I suspect that this is failing due to needing to specify the --all-features flag. I'll investigate and get another release out

**Comment by jblindsay** [comment]
@sdd Thanks for your response. No worries at all, I completely understand and sympathize with being inundated by such requests.

**Comment by oxlade39** [comment]
If it helps I just ran on the latest `nightly-x86_64-pc-windows-msvc` using `--all-features` and it compiled with 2 warnings.

**Comment by sdd** [comment]
Ha, cheers Dan. That's what I've been using during development, and in the projects that I have that consume kiddo - pass the `--all-features` flag whenever I call cargo. But, I need to work out a way to fix things so that consumers don't need to do the same.

**Comment by sdd** [comment]
I think [this](https://github.com/sdd/kiddo/pull/5) should fix it

**Comment by sdd** [comment]
Fixed, released as 0.1.4 - please let me know if you still experience any issues with this.

**Comment by jblindsay** [comment]
I think that perhaps my issues for compilation are because I am using an M1 mac. Is there a platform dependency in this library somehow?

**Comment by sdd** [comment]
@jblindsay I know that this was a while ago now but does v0.1.5 fix your issue?

I'm hoping to get my hands on a shiny new 14" MBP once they get released later this year so if 0.1.5 doesn't fix the problem, I'll be able to dig into it on my own M1 / M1X machine :-)

**Comment by jblindsay** [comment]
No, I'm afraid that I was still unable to compile. I think you'll like you M1X machine. The M1 is pretty darn impressive so one can only imagine M1X!
